[16.0][MIG] stock_orderpoint_mto_as_mts
OCA/stock-logistics-orderpoint pull request #14
Opened 2024-04-16 08:24 UTC by tuantrantg

Notes:
* WIP: working on the TODO
* Renamed sale_stock_mto_as_mts_orderpoint to stock_orderpoint_mto_as_mts
* Removed dependency on stock_orderpoint_manual_procurement as not needed anymore, see https://github.com/OCA/stock-logistics-warehouse/pull/1641
* Used `is_mto` on product (depend on product-attribute/product_route_mto)
* Used `is_mto` on route instead of xmlid (provided by stock-logistics-warehouse/stock_route_mto - already pulled by product_route_mto)
* Performed the bellow in `product.product`:
  * Processed: the orderpoint must be created only for warehouses where there is no mto rule for that warehouse
  * Moved the orderpoint archiving from `product.template` and refactored it
* Made the orderpoint archiving configurable on the warehouse
* Droped `is_from_mto_route` on `stock.move`. That should not be in this module, not related to orderpoint

2024-04-16 10:50 UTC, jbaudoux requested changes

2024-04-16 10:50 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/stock_warehouse.py
> +        return self.mapped("lot_stock_id")
Can you depend on https://github.com/OCA/stock-logistics-orderpoint/pull/5/files#diff-34ce65f805726da9a9ebaedb97f0d4188d1335149786f5d37cf07008811ea0ddR11 ?

```suggestion
        self.ensure_one()
        return self.default_orderpoint_location_id or self.lot_stock_id
```

2024-04-16 10:50 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +            company = company or default_company
If there is no company, then the product is valid for all companies, not just the main one. You then need to get all warehouses

2024-04-16 10:50 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +                if not product.is_missing_default_orderpoint_for_mto:
This needs to be refactored as you need to know for which warehouse it is missing. Maybe drop the computed field

2024-04-16 10:50 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +            warehouses = self.env["stock.warehouse"].search(
You need to filter out the warehouses for which we want mto as mts. Ideally as an option on the warehouse.

2024-04-17 04:16 UTC, tuantrantg commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +            warehouses = self.env["stock.warehouse"].search(
Hi @jbaudoux please review these again

2024-04-19 05:50 UTC, santostelmo approved these changes
LG good with @jbaudoux changes

2024-04-23 10:25 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +            wh_wo_orderpoint = wh.filtered(lambda r: r not in wh_orderpoint)
You mean?
```suggestion
            wh_orderpoint = product.orderpoint_ids.warehouse_id
            wh_wo_orderpoint = wh - wh_orderpoint
```

2024-04-23 10:27 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +                limit=1,
To prevent useless sorting cost, always better to set order when limit=1
```suggestion
                limit=1, order="id"
```

2024-04-23 10:30 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +        for product in self:
Maybe use ensure_one() and return wh_wo_orderpoint instead of dict

2024-04-23 10:31 UTC, jbaudoux commented on test-requirements.txt
> +odoo-addon-stock-orderpoint-default-location @ git+https://github.com/OCA/stock-logistics-orderpoint.git@refs/pull/5/head#subdirectory=setup/stock_orderpoint_default_location
This can now be dropped

2024-04-25 12:33 UTC, santostelmo requested changes

2024-04-25 12:33 UTC, santostelmo commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +        for product in self:
```suggestion
        for product in self:
            if not product.purchase_ok:
                continue
```
There's no point to create a orderpoints for products that can not be purchased.

That is in conflict with the validation done in `purchase_reorder_control`
_Unpurchaseable Products cannot be reordered_
https://github.com/OCA/purchase-workflow/blob/e113f0a3a046ad832f2e324df50301c276932fa4/purchase_reorder_control/models/stock_warehouse_orderpoint.py#L21

2024-05-07 13:19 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +        for product in self:
drop for loop as you have `ensure_one()`

2024-05-07 13:21 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +            wh = product._get_warehouse_missing_orderpoint_for_mto()
I don't see where you check it is a mto product
```
mto_products = self._filter_mto_products()
```

2024-05-07 13:21 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +        # Archive orderpoints when MTO route is removed
this comment is misplaced

2024-05-07 13:31 UTC, rousseldenis commented
/ocabot migration stock_orderpoint_mto_as_mts

2024-05-07 13:40 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +    def write(self, vals):
You need to look in`vals` for `is_mto` or `company_id`. Those are on `product.template`, so you need to move the hook to write on the right model

2024-05-07 13:48 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/stock_warehouse.py
> +    mto_as_mts = fields.Boolean(default=False)
When you flag this, you could archive from the MTO route the rule for this warehouse

2024-05-07 14:04 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/product_product.py
> +    def write(self, vals):
I don't really understand the method
```
res = super().write(vals)
if vals.get("is_mto"):
    # when is_mto is set
    self.sudo()._ensure_default_orderpoint_for_mto()
elif not vals.get("is_mto", True):
    # when is_mto is removed
    self.sudo()._archive_orderpoints_on_mto_removal()
elif "company_id" in vals:
    # when company is changed
    self.sudo()._archive_orderpoints_on_mto_removal()
    self.sudo()._ensure_default_orderpoint_for_mto()
return res
```

2024-05-07 14:07 UTC, jbaudoux commented on stock_orderpoint_mto_as_mts/models/stock_warehouse.py
> +    mto_as_mts = fields.Boolean(default=False)
`default=False` is useless

2024-05-27 08:00 UTC, closed without merging